src/pages/account/resetPassword.vue

Login Signup ResetPasswordの実装

---

.github/workflows/reviewdog.yml
Dockerfile
README.md
docker-compose.yml

dockerで動くようにしました
reviewdogも付けました

add Docker files

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
FOR_DEVELOPERS.md

Fix: .mdの微調整 #41
単語の修正、Markdown linterの指摘事項の一部対応、程度の対応です。

いくつかの .md を調整

---

src/middleware/authenticated.ts

autenticated ミドルウェアのTS化

---

nuxt.config.js
src/layouts/classes.vue
src/pages/classes/index.vue
src/plugins/dayjs.js
src/types/vue-shims.d.ts

Dayjsのinjectを解除

---

src/components/LessonCaption.vue

Add component for title of lesson

---

src/components/AddButton.vue

Add component AddButton < #65

---

package.json

#82 の追加分という扱いです。
#82 で指摘のあった変更の内、`typescript` も不要なので削除しました。

package.json から typescript を削除

---

src/components/CalendarBar.vue
src/layouts/classes.vue
src/pages/classes/index.vue

カレンダーバーに合わせて表示を行うように変更

---

src/components/AddButton.vue
src/components/LessonCaption.vue
src/components/SimpleBottomSheet.vue
src/components/__tests__/CalendarBar.spec.ts

- #69 で課題となっていたスクロール可能な表現を実装しCSSを調整
- LessonCaption、CSSのリファクタリング
- #97 (PR) 含む

v-bottom-sheet を利用したシートの改善

---

src/components/ActionButton.vue
src/components/EditingScreen.vue
src/components/EditingScreen1.vue
src/components/EditingScreen2.vue
src/components/EditingScreen3.vue
src/components/EditingScreen4.vue
src/components/EditorField.vue
src/components/EditorInputField.vue
src/components/EditorTextarea.vue
src/components/InputField.vue
src/components/SimpleBottomSheet.vue
src/components/VideoThumbnail.vue
src/pages/edit/index.vue

close #117 
TODO:
- ~~InputFieldでフィールド内部のアイコンの表示非表示が切り替えられるようにしたい。~~
→ 新規コンポーネントを作成
- ~~スタイルの確認。~~
[![Image from Gyazo](https://i.gyazo.com/8cbec1b0d88b1e6e26f7662e75011160.gif)](https://gyazo.com/8cbec1b0d88b1e6e26f7662e75011160)

授業の編集・追加画面作成

---

src/components/BottomSheetLayer.vue
src/layouts/background.vue
src/pages/user/classlist.vue

close #122 
ラジオボタン、ボタンの挙動は未実装です。

クラス選択ページ作成

---

src/pages/user/signup.vue

close #123 
- すべてのフィールドにrequiredをつけておきました。
- inputフィールド・ボタンの挙動は未実装です。
- `InputField.vue` を調整する必要があるかもしれませんが（labelとplaceholderのあたりとか）、とりあえずこのPRでは触れていません。
- スクロールバーのスタイルはブラウザ依存だと思われるので、とりあえず放置してます。

ユーザー登録ページ作成

---

src/components/PeriodCard.vue
src/components/PeriodCardEditable.vue
src/layouts/classes.vue
src/pages/classes/index.vue
src/pages/edit/index.vue
src/store/index.ts
src/store/modules/app.ts
src/store/modules/classData.ts

displayDateのVuex Store分離・名前変更とリファクタリング

---

src/pages/user/registerClass.vue
src/pages/user/registered.vue

close #124
- 両方ともpagesで作成しました。
- Vuetifyのv-text-fieldはフィールドの下にメッセージ用のエリアがあるので、フィールド下部に隙間があくことになります。

クラス登録ページ・登録完了ページ作成

---

src/store/modules/classData.ts
src/types/store/classData.d.ts

新Lessons形式に対応する

---

src/components/ActionButton.vue
src/components/BottomSheetLayer.vue
src/components/EditingScreen.vue
src/components/SimpleBottomSheet.vue
src/pages/account/login.vue

ログインページの作成

---

src/components/EditingScreen.vue
src/pages/account/login.vue
src/pages/index.vue

v-snackbar に v-model で error を渡す

---

src/pages/lesson/index.vue

close #218 修正完了しました。
レビューお願いします。
https://github.com/codeforjapan/StudyAtHome/issues/218

Bugfix/fix 23　時間割詳細で「学習の目的と参考動画」を表示

---

nuxt-i18n.config.js
nuxt.config.js
package.json
src/assets/locales/ja.json
src/components/BaseDialog.vue
src/components/ContentCard.vue
src/components/EditingScreen.vue
src/components/EditingScreen1.vue
src/components/EditingScreen2.vue
src/components/EditingScreen3.vue
src/components/EditingScreen4.vue
src/components/EditingVisibilityDialog.vue
src/components/SubjectTag.vue
src/layouts/classes.vue
src/layouts/lesson.vue
src/layouts/protected.vue
src/layouts/simple.vue
src/pages/classes/index.vue
src/pages/classes/terms.vue
src/pages/edit/index.vue
src/pages/index.vue
src/pages/lesson/index.vue
src/pages/user/classlist.vue
src/pages/user/editUserData.vue
src/pages/user/login.vue
src/pages/user/registerClass.vue
src/pages/user/registered.vue
src/pages/user/signup.vue
tsconfig.json
yarn.lock

nuxt-i18nの導入・日本語言語ファイルの追加

---

src/components/AppLanguageSelector.vue
src/layouts/background.vue
src/layouts/classes.vue
src/layouts/default.vue
src/layouts/lesson.vue
src/layouts/protected.vue
src/layouts/simple.vue

言語選択ボックスを仮設置

---

src/pages/index.vue
src/store/modules/classData.ts

loadClassDataからはAPI KEY認証を外しました。

API KEY認証は生徒側ログインのみにする

---

src/assets/locales/ja.json
src/components/EditLessonScreenInner2.vue
src/components/EditLessonScreenInner3.vue

- 重複していた翻訳を除去
- 動画検索機能に使用する文字列を翻訳可能に

翻訳の追加・更新（2020/09/26）

---

src/components/EditLessonScreen.vue
src/components/PeriodSection.vue
src/layouts/classes.vue
src/layouts/protected.vue
src/pages/classes/index.vue
src/pages/edit/index.vue
src/pages/index.vue
src/pages/lesson/index.vue
src/pages/user/editUserData.vue
src/pages/user/logout.vue
src/store/modules/app.ts
src/store/modules/classData.ts
src/store/modules/user.ts
src/types/store/classData.d.ts

- lessonsを日付ごとに取得するようにしました
- authModeを生徒側と先生側で分けました
- その他もろもろ不具合修正しました

graphqlによりstoreを大幅に改修

---

.graphqlconfig.yml
amplify/backend/api/studyathome/schema.graphql
src/API.ts
src/graphql/mutations.ts
src/graphql/queries.ts
src/graphql/subscriptions.ts
src/pages/index.vue
src/pages/user/classlist.vue
src/store/modules/classData.ts
src/store/modules/user.ts

APIレベルで学校名の表示を一般ユーザーから物理的に読み込み不可能とするための改修です。DBスキーマの変更が必要となりますので、マージタイミングは相談します。

[DB Schema should be fixed] Hide school name for public students

---

src/store/modules/classData.ts

Fix bug for student

---

src/pages/user/classlist.vue
src/store/modules/classData.ts
tsconfig.json

必要最低限のattributeを持つqueryに書き換えました。
- listClasss -> listClasssSimple
- getClass -> getClassSimple
- listLessonsByClass -> listLessonsByClassSimple

不要なattributeを取り除いたqueryを追加

---

nuxt.config.js
package.json
yarn.lock

Add Google Analytics

---

src/types/store/classData.d.ts

interfaceの順番を修正（eslintエラー解消）

---

src/pages/user/registerClass.vue
src/store/modules/classData.ts

クラスID生成多言語対応

---

src/components/BaseInputField.vue
src/pages/index.vue

classIdPatternの正規表現を多言語対応

---

src/middleware/authenticated.ts
src/middleware/checkClassData.ts
src/pages/user/signup.vue

多言語化漏れを対応（redirectのpath, passwordConfirmのメッセージ直書き）

---

src/pages/user/signup.vue

`nuxt generate` で吐いていたエラーを修正しました。

typeを追加（nuxt generateのエラー対応）

---

nuxt.config.js
src/middleware/authenticated.ts
src/pages/index.vue
src/pages/user/classlist.vue
src/pages/user/editUserEmail.vue
src/pages/user/editUserName.vue
src/pages/user/editUserPassword.vue
src/pages/user/login.vue
src/pages/user/logout.vue
src/pages/user/signup.vue
src/pages/user/verify.vue
src/pages/user/verifyNewEmail.vue
src/plugins/amplify.ts
src/store/modules/classData.ts
src/store/modules/user.ts

SSR時の通信の状態は要検討。時間がかかりそうなので、いったんssr:falseに戻す。

ssr:falseに戻す

---

package.json
yarn.lock

dependabotのPRを参考にpackageをアップデートしました。

packageアップデート

---

renovate.json

renovate.jsonがダブっていたので古いほうを削除
